# Configuration files for surrogate calibration
plots_for_esco: False

# Options for creating surrogate model
datadir: ../../data 
savedir: ../../models 

season: DJF # DJF, MAM, JJA, SON

nyear: 10 # 5, 10

fields: [PRECT] # [SWCF, LWCF, PRECT]

target_type: full # full, zonal, scalar, custom function (not implemented yet)

resolution: 180x360

custom_scalar_function: 
  file: #custom_scalar_function.py

# Options for surrogate model method, e.g., ROM, neural networks, etc.
# Not implemented yet
surrogate:
  fit: True
  options:
    method: pce
    n_components: 16 # int, auto (90% exp. variance)
    compute_cv_score: True
    compute_raw_cv_scores: False

# Options for optimization and Bayesian inference
# (Not implemented yet)
calibration:
  optimize:
    method: MLE # MAP, MLE, MLE_msigma
    options: 
      plot_diagnostics: False
      weights: # e.g., null, [1,1,1], [1,.25,0]
  Bayesian: 
    MCMC: False # not implemented yet

validation:
  surrogate: False
  e3sm: False
  optimization: MAP # MLE, MAP
  plot: False
  plot_options: e3sm # e3sm, surrogate, both
