# Configuration files for surrogate calibration
plots_for_esco: False

# Options for creating surrogate model
datadir: ../../data 
savedir: ../../surrogate_models 

season: ANN # DJF, MAM, JJA, SON

nyear: 10 # 5, 10

fields: [SWCF, LWCF, PRECT, PSL, Z500,  U200, U850, TREFHT] # [SWCF, LWCF, PRECT]

target_type: full # full, zonal, scalar, custom function (not implemented yet)

resolution: 180x360

subtract_ens_mean: FALSE

# cv scores for 180x360 
# SWCF, LWCF, PRECT:
# 0.59, 0.59, 0.21 (avg = .46333)
# vs combined:
# 0.458

custom_scalar_function: 
  file: #custom_scalar_function.py

custom_surrogate_fit_function: 
  file: #custom_surrogate_fit_function.py

# Options for surrogate model method, e.g., ROM, neural networks, etc.
# Not implemented yet
surrogate:
  fit: True
  options:
    method: pce
    n_components: 16 # int, auto (90% exp. variance)
    compute_cv_score: True
    compute_raw_cv_scores: False
    save_predictions: True
    save_pcs: True

# Options for optimization and Bayesian inference
# (Not implemented yet)
calibration:
  optimize:
    method: MAP # MAP, MLE, MLE_msigma
    options: 
      plot_diagnostics: False
      weights: # e.g., null, [1,1,1], [1,.25,0]
  Bayesian: 
    MCMC: False # not implemented yet

validation:
  surrogate: False
  e3sm: False
  optimization: MAP # MLE, MAP
  plot: False
  plot_options: e3sm # e3sm, surrogate, both
