#### Specify cost function, save details, and surrogate ####
cost_function: cost_function_template.py

savename: test

savedir: # where to save output (optional; default is the surrogate directory)

surrogate: /global/cfs/cdirs/e3sm/emulate_paper/surrogate_models/surrogate_provenance_test_20260407170515 # directory where the surrogate is stored 

#### Specifications for Optimization and Validation ####
data: 
    obs_path: /global/cfs/cdirs/e3sm/emulate_paper/data/obs/*obs_dnet-1.5_RESTOM2.5.nc
    ens_path: /global/cfs/cdirs/e3sm/emulate_paper/data/ensemble/*ensemble.nc
    val_path: /global/cfs/cdirs/e3sm/emulate_paper/data/validation/*.nc

param_bounds:
    clubb_c1: [1.0, 5.0]
    clubb_gamma_coef: [0.1, 0.5]
    zmconv_tau: [1800.0, 14400.0]
    zmconv_dmpdz: [-2.e-3, -0.1e-3]
    zmconv_micro_dcs: [100.e-6, 400.e-6] # 0.00015 # 
    nucleate_ice_subgrid: [1.20, 1.40] # 1.35 # 
    p3_nc_autocon_expon: [-1.79, -0.70]
    p3_qc_accret_expon: [1.10, 1.30]
    zmconv_auto_fac: [3.0, 7.5] # 7.0 # 
    zmconv_accr_fac: [1.5, 2.0] # 1.5 # 
    zmconv_ke: [0.5e-6, 10.e-6] # 2.5e-6 # 
    cldfrc_dp1: [0.01, 0.10]
    p3_embryonic_rain_size: [15.e-6, 40.e-6] # 2.5e-5 # 
    p3_mincdnc: [7.5e6, 30.e6] # 7.5e6 # 

optimization:
    run: True 
    param_start: # list of initial values for optimization algorithm (optional; default is random initialization) 
    seed: # set for reproducibility (optional) 
    # use_response_transforms: # {bool} (True: use response transforms from surrogate, False: no response transforms) -- NOT IMPLEMENTED YET

validation: 
    modsim: # validate all modsims in "datadir" against obs
        run: True 
    surrogate: # validate surrogate predictions of all modsims in "datadir" against obs
        run: True 
        save_predictions: True
        param_paths: # paths to files containing additional parameter sets to be validated
    val_workdirs: # (user_chosen_key: workdir)
        ctrl: /pscratch/sd/w/wagmanbe/E3SM_simulations/dakota/v3_pmcpu/ne30_F2010/ctrl/20230802.v3alpha02.F2010.pmcpu.intel.8N #cannot comment out this section entirely, have to give an empty string...should be an optional parameter given that one can specify validation files above as well.
        lowECS001: /pscratch/sd/w/wagmanbe/E3SM_simulations/dakota/v3_pmcpu/ne30_F2010/ens/workdir.293/20230802.v3alpha02.F2010.pmcpu.intel.8N
        lowECS002: /pscratch/sd/w/wagmanbe/E3SM_simulations/dakota/v3_pmcpu/ne30_F2010/validate/validate.dnet-2.1_RESTOM-0.5_rw2_20240531132555
        lowECS003: /pscratch/sd/w/wagmanbe/E3SM_simulations/dakota/v3_pmcpu/ne30_F2010/validate/validate.dnet-2.1_RESTOM-0.5_highR2_20240531093356 
        highECS001: /pscratch/sd/w/wagmanbe/E3SM_simulations/dakota/v3_pmcpu/ne30_F2010/validate/validate.v3alpha02.2023102
        highECS002: /pscratch/sd/w/wagmanbe/E3SM_simulations/dakota/v3_pmcpu/ne30_F2010/validate/validate.opt_params_dnet-1.5_reweight_mincdnc12.5e6_20240423132337 
        highECS003: /pscratch/sd/w/wagmanbe/E3SM_simulations/dakota/v3_pmcpu/ne30_F2010/validate/validate.dnet-1.5_RESTOM2.5_20240530123051
########


#### Machine details ####
n_cores: n_cores_half
machine: perlmutter 
########
