machine: perlmutter 

data: 
    obs_path: /global/cfs/cdirs/e3sm/emulate/data/test_new_preprocessing/obs/*obs_dnet-1.5_RESTOM2.5.nc
    ens_path: /global/cfs/cdirs/e3sm/emulate/data/test_new_preprocessing/ensemble/*ensemble.nc

provenance_repo: /global/cfs/cdirs/e3sm/emulate/surrogate_models/test_new_preprocessing

savename: test

responses: 
    ANN:
        RESTOM: RESTOM
        dnet_cld_dir: dnet_cld_dir
    DJF:
        DJF_SWCF: SWCF
        DJF_LWCF: LWCF
        DJF_PRECT: PRECT
        DJF_TREFHT: TREFHT
        # DJF_PSL: PSL
        DJF_Z500: Z500
        # DJF_U850: U850
        DJF_U200: U200
        DJF_RELHUM: RELHUM
        DJF_T: T
        # DJF_U: U
    MAM:
        MAM_SWCF: SWCF
        MAM_LWCF: LWCF
        MAM_PRECT: PRECT
        MAM_TREFHT: TREFHT
        # MAM_PSL: PSL
        MAM_Z500: Z500
        # MAM_U850: U850
        MAM_U200: U200
        MAM_RELHUM: RELHUM
        MAM_T: T
        # MAM_U: U
    JJA:
        JJA_SWCF: SWCF
        JJA_LWCF: LWCF
        JJA_PRECT: PRECT
        JJA_TREFHT: TREFHT
        # JJA_PSL: PSL
        JJA_Z500: Z500
        # JJA_U850: U850
        JJA_U200: U200
        JJA_RELHUM: RELHUM
        JJA_T: T
        # JJA_U: U
    SON:
        SON_SWCF: SWCF
        SON_LWCF: LWCF
        SON_PRECT: PRECT
        SON_TREFHT: TREFHT
        # SON_PSL: PSL
        SON_Z500: Z500
        # SON_U850: U850
        SON_U200: U200
        SON_RELHUM: RELHUM
        SON_T: T
        # SON_U: U

n_cores: n_cores_half

surrogate:
    fit_new: True 
    provenance_dir: # path from provenance_repo to surrogate_provenance dir (if fit_new is False) 
    model_load_file: # Path from provenance dir to surrogate model if fit_new is False.
    param_bounds:
        clubb_c1: [1.0, 5.0]
        clubb_gamma_coef: [0.1, 0.5]
        zmconv_tau: [1800.0, 14400.0]
        zmconv_dmpdz: [-2.e-3, -0.1e-3]
        zmconv_micro_dcs: [100.e-6, 400.e-6]
        nucleate_ice_subgrid: [1.20, 1.40]
        p3_nc_autocon_expon: [-1.79, -0.70]
        p3_qc_accret_expon: [1.10, 1.30]
        zmconv_auto_fac: [3.0, 7.5]
        zmconv_accr_fac: [1.5, 2.0]
        zmconv_ke: [0.5e-6, 10.e-6]
        cldfrc_dp1: [0.01, 0.10]
        p3_embryonic_rain_size: [15.e-6, 40.e-6]
        p3_mincdnc: [5.0, 30.e6]
    enforce_bounds: True # exclude any ensemble members whose params fall outside the bounds

    response_transforms: # {log, sqrt, {k}root}
    
    response_weights:
        dnet_cld_dir: 4.0

    stdz_by_ncol: True
    norm_method: /global/cfs/cdirs/e3sm/emulate/data/pi_temporal_std/pi_temporal_std.pkl # {"obs_field_std", "obs_field_median", "obs_field_q{k}", "ens_col_std", {file_name}}
    n_components: 2
    surrogate_scorer: neg_root_mean_squared_error
    method: pce
    
cv:
    run: True
    full_cv: False # estimate pcs and hyperparameters for each training set (not currently working...)
    method: random # random or kfold 
    nsplits: 3 
    nsim: 100 # if nsim!=all, use method='random'. Otherwise, some sims will be ignored in all folds.
    ntest: 50 # only used if method=random
    test_condition: # only ensemble members meeting these criteria can enter test sets

sensitivity:
    run: True
    plot: True
    save: True
