machine: perlmutter

savedir: /global/cfs/cdirs/e3sm/emulate_paper/data/test_preprocessing

verbose: False # print warnings every time data are unavailable in a directory (which is often expected)?

obs:
    process: False
    name: obs_dnet-1.5_RESTOM2.5

    # obs file path is {srcdir}/{file}
    srcdirs:
        ANN: /global/cfs/cdirs/e3sm/emulate/obs/targets_v3/scalar_obs
        DJF: /global/cfs/cdirs/e3sm/emulate/obs/targets_v3/merged
        MAM: /global/cfs/cdirs/e3sm/emulate/obs/targets_v3/merged
        JJA: /global/cfs/cdirs/e3sm/emulate/obs/targets_v3/merged
        SON: /global/cfs/cdirs/e3sm/emulate/obs/targets_v3/merged

    files:
        ANN: 
            - obs_ANN_RESTOM2.5.nc
            - obs_ANN_dnet_cld_dir_-1.5.nc
        DJF:
            - obs_merged_DJF_24x48.nc
        MAM:
            - obs_merged_MAM_24x48.nc
        JJA:
            - obs_merged_JJA_24x48.nc
        SON:
            - obs_merged_SON_24x48.nc

    obs_variable_names:
        ANN: [RESTOM, dnet_cld_dir]
        DJF: [SWCF, LWCF, PRECT, TREFHT, PSL, Z500, U850, U200, RELHUM, T, U, lat, lon, lev, area]
        MAM: [SWCF, LWCF, PRECT, TREFHT, PSL, Z500, U850, U200, RELHUM, T, U, lat, lon, lev, area]
        JJA: [SWCF, LWCF, PRECT, TREFHT, PSL, Z500, U850, U200, RELHUM, T, U, lat, lon, lev, area]
        SON: [SWCF, LWCF, PRECT, TREFHT, PSL, Z500, U850, U200, RELHUM, T, U, lat, lon, lev, area]


model:
    datasets: 
        ensemble:
            process: True
            paths:
                - ens/workdir.*/20230802.v3alpha02.F2010.pmcpu.intel.8N
                - hm/*
                - validate/validate.opt_params_high_10e6.v3a02.20231221
                - validate/validate.opt_params_dnet-1.5
                - validate/validate.opt_params_dnet-1.5_rawprecip_20240430134907
                - validate/validate.opt_params_med_weighted.v3a02.20240111
                - validate/validate.opt_params_dnet-2.1_all_20240510130950 
                - validate/validate.opt_params_dnet-2.1_sqrtprecip_20240430163849
                - validate/validate.opt_params.v3a02.20240111
                - validate/validate.opt_params_dnet-2.1_reweight_mincdnc10e6_20240423092413
                - validate/validate.opt_params_dnet-2.1_mincdnc12.5e6_20240418181633
                - validate/validate.opt_params_dnet-2.1_reweight_mincdnc12.5e6_20240423101127 
                - validate/validate.opt_params_low_weighted.v3a02.20231221
                - validate/validate.opt_params_dnet-2.1_mincdnc7.5e6_20240418180837
                - validate/validate.opt_params_dnet-2.1_rawprecip_20240430153611
                - validate/validate.opt_params_dnet-1.5_reweight_20240423104748
                - validate/validate.opt_params_dnet-1.5_reweight_mincdnc7.5e6_20240423124952 
                - validate/validate.v3alpha02.2023102
                - validate/validate.dnet-1.5_opt_20240523084559
                - validate/validate.opt_params_dnet-2.1_reweight_20240423085041 
                - validate/validate.opt_params_dnet-1.5_reweight_mincdnc12.5e6_20240423132337 
                - validate/validate.dnet-2.1_opt_rw2_20240523104406
                - validate/validate.opt_params_dnet-1.5_all_20240510123524
                - validate/validate.opt_params_dnet-1.5_reweight_mincdnc10e6_20240423130448 

        validation:
            process: False
            paths:
                - ctrl/20230802.v3alpha02.F2010.pmcpu.intel.8N
                - validate/*
                - ens/workdir.293/20230802.v3alpha02.F2010.pmcpu.intel.8N # lowECS001

    responses:
    # file path for model output is {srcdir}/{workdir}/{file}
        srcdirs: 
            ANN: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010
            DJF: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010
            MAM: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010
            JJA: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010
            SON: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010
        
        files:
            ANN:
                - targets/atm/24x48_aave/5yr/*_ANN_000201_000612_merged.nc
               # - targets/atm/24x48_aave/5yr/*_ANN_000201_000612_feedbacks_lat_lon.nc
            DJF:
                - targets/atm/24x48_aave/5yr/*_DJF_000201_000612_merged.nc
            MAM: 
                - targets/atm/24x48_aave/5yr/*_MAM_000203_000605_merged.nc
            JJA:
                - targets/atm/24x48_aave/5yr/*_JJA_000206_000608_merged.nc        
            SON:
                - targets/atm/24x48_aave/5yr/*_SON_000209_000611_merged.nc

        model_variable_names: 
            ANN: [FLNT, FSNT, dnet_cld_dir, area]
            DJF: [SWCF, LWCF, PRECT, TREFHT, PSL, Z500, U850, U200, RELHUM, T, U, lat, lon, lev, area]
            MAM: [SWCF, LWCF, PRECT, TREFHT, PSL, Z500, U850, U200, RELHUM, T, U, lat, lon, lev, area]               
            JJA: [SWCF, LWCF, PRECT, TREFHT, PSL, Z500, U850, U200, RELHUM, T, U, lat, lon, lev, area]
            SON: [SWCF, LWCF, PRECT, TREFHT, PSL, Z500, U850, U200, RELHUM, T, U, lat, lon, lev, area]              
        model_to_obs_transforms:
            ANN:
                RESTOM: "np.multiply(FSNT - FLNT, area).sum() / area.sum()"
                dnet_cld_dir: "np.multiply(dnet_cld_dir, area).sum() / area.sum()"
            DJF: 
                PRECT: "86400000.0 * PRECT"
            MAM: 
                PRECT: "86400000.0 * PRECT"                
            JJA: 
                PRECT: "86400000.0 * PRECT"            
            SON: 
                PRECT: "86400000.0 * PRECT"

    params:
        # file path for input params is {srcdir}/{workdir}/{file} 
        srcdirs: 
            ANN: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010
            DJF: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010
            MAM: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010
            JJA: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010
            SON: /global/cfs/cdirs/e3sm/emulate/postproc_e3sm/v3_merged_targets/ne30_F2010

        file: run/atm_in
        file_type: atm_in # {atm_in, xml}
        param_names:
            - clubb_c1
            - clubb_gamma_coef
            - zmconv_tau
            - zmconv_dmpdz
            - zmconv_micro_dcs
            - nucleate_ice_subgrid
            - p3_nc_autocon_expon
            - p3_qc_accret_expon
            - zmconv_auto_fac
            - zmconv_accr_fac
            - zmconv_ke
            - cldfrc_dp1
            - p3_embryonic_rain_size
            - p3_mincdnc
